### ISSUE TITLE
UI - execution status and error messages

### ISSUE THREAD

**Issue by georgesnelling** [lyft/flyte#74] opened 2019-11-19 17:53 UTC
If an execution fails, I have to go back to the workflow page in order to see the error.  I'd like to be able to see the error on the actual execution page as well.  I feel like I have to go back currently, make sure i'm looking at the right execution (cuz there are sometimes a lot of executions), and then hop back and forth.

**Comment by schottra** [comment] 2020-07-01 19:57
Closing as a duplicate of #319

**Closed by schottra** 2020-07-01 19:57 UTC
Labels: pri2, task, trust, ui
