### ISSUE TITLE
[BUG] Execution list view overlaps the rows after "Load More" in case of failures

### ISSUE THREAD

**Issue by kumare3** [lyft/flyte#509] opened 2020-09-14 16:30 UTC
**Describe the bug**
For the executions list view, after a page full of success, a new page is loaded using load more and if the new page has an error (un-collapsed) then the view gets overlapped, making it hard to read and click on. This cannot be fixed by re-loading

<img width="2697" alt="Screen Shot 2020-09-14 at 9 25 46 AM" src="https://user-images.githubusercontent.com/16888709/93112215-91b9df80-f66c-11ea-81c4-dc4f49497bca.png">

**Expected behavior**
The view should adjust to the width

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [x] FlyteConsole (UI)
- [ ] Other

**To Reproduce**
Choose a project with all success and load more

**Screenshots**
attached!

**Comment by schottra** [comment] 2020-09-22 17:14
Closing as a duplicate of #507

**Closed by schottra** 2020-09-22 17:14 UTC
Labels: bug, ui, untriaged
