### ISSUE TITLE
[BUG] Flyte console "Status" filter is not working as expected

### ISSUE THREAD

**Issue by bnsblue** [lyft/flyte#546] opened 2020-10-12 18:01 UTC
**Describe the bug**
When I used the `status` filter, the behavior is erroneous. If you check the "Failed" box, the console only brings up some of the older failed executions. For example, in our `hive.ExampleQueryWorkflow`, there have been 2 failed execution on 10/12. If I check the `Failed` box, the console only brings up the failed executions older than 9/27.

Also, after unchecking the box, the console will not be able to bring back the entire up-to-date list of executions. It doesn't show the latest batch of executions; the latest ones it shows were some of the older executions that started 12 hours ago. 

Not sure if this bug only affects the `status` filter or if all the other filters experience the same bug.

**Expected behavior**
Using the filter should bring up a correct and up-to-date list of recent executions that satisfy the filter value. Unchecking the filters should bring up the correct and up-to-date list of all recent executions.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [x] FlyteConsole (UI)
- [ ] Other

**To Reproduce**
1. ...
2. ...

**Screenshots**

Right after entering the workflow view (i.e., **the "correct" outcome**):
![image](https://user-images.githubusercontent.com/1518524/95776794-dc357880-0c79-11eb-9f55-bc08a2c37dad.png)

After checking the "Failed" filter box. You can see that the latest failed execution is not shown
![image](https://user-images.githubusercontent.com/1518524/95776828-ece5ee80-0c79-11eb-8e91-dc8073cd8c90.png)

After unchecking the filter. You can see that the list doesn't match **the correct outcome** shown above.
![image](https://user-images.githubusercontent.com/1518524/95776845-f66f5680-0c79-11eb-82ae-cf3bdb150f17.png)

**Environment**
**Flyte component**
- [ ] Sandbox (local or on one machine)
- [ ] Cloud hosted
     * [x] AWS
     * [ ] GCP
     * [ ] Azure
- [ ] Baremetal
- [ ] Other

**Additional context**

**Comment by katrogan** [comment] 2020-10-12 18:38
@bnsblue could this be a dupe of https://github.com/lyft/flyte/issues/539 ?

**Comment by schottra** [comment] 2020-10-13 18:13
Looks like Console isn't clearing the `token` when changing filters, which results in fetching further and further back in the history every time you change a filter.

**Comment by schottra** [comment] 2020-10-16 19:00
Fixed by lyft/flyteconsole#105
Available in flyteconsole v0.13.2

**Closed by schottra** 2020-10-16 19:00 UTC
Labels: bug, ui
