### ISSUE TITLE
Trying to register a workflow gives failed to connect to all addresses

### ISSUE THREAD

**Issue by sniazhana-p** [lyft/flyte#166] opened 2020-02-05 19:05 UTC
Trying to follow the docs to run flyte locally with docker run:
`docker run --network host -e FLYTE_PLATFORM_URL='127.0.0.1:30082' lyft/flytesnacks:v0.1.0 pyflyte -p flytesnacks -d development -c sandbox.config register workflows`

Give an error:

>  Traceback (most recent call last):
>   File "/app/venv/bin/pyflyte", line 11, in <module>
>     sys.exit(main())
>   File "/app/venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/app/venv/lib/python3.6/site-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/app/venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/app/venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/app/venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/app/venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/app/venv/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/app/venv/lib/python3.6/site-packages/flytekit/clis/sdk_in_container/register.py", line 86, in workflows
>     register_all(project, domain, pkgs, test, version)
>   File "/app/venv/lib/python3.6/site-packages/flytekit/clis/sdk_in_container/register.py", line 24, in register_all
>     o.register(project, domain, name, version)
>   File "/app/venv/lib/python3.6/site-packages/flytekit/common/exceptions/scopes.py", line 158, in system_entry_point
>     return wrapped(*args, **kwargs)
>   File "/app/venv/lib/python3.6/site-packages/flytekit/common/tasks/task.py", line 141, in register
>     _engine_loader.get_engine().get_task(self).register(id_to_register)
>   File "/app/venv/lib/python3.6/site-packages/flytekit/engines/flyte/engine.py", line 234, in register
>     self.sdk_task
>   File "/app/venv/lib/python3.6/site-packages/flytekit/clients/friendly.py", line 50, in create_task
>     spec=task_spec.to_flyte_idl()
>   File "/app/venv/lib/python3.6/site-packages/flytekit/clients/raw.py", line 12, in handler
>     return fn(*args, **kwargs)
>   File "/app/venv/lib/python3.6/site-packages/flytekit/clients/raw.py", line 77, in create_task
>     return self._stub.CreateTask(task_create_request)
>   File "/app/venv/lib/python3.6/site-packages/grpc/_channel.py", line 604, in __call__
>     return _end_unary_response_blocking(state, call, False, None)
>   File "/app/venv/lib/python3.6/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
>     raise _Rendezvous(state, None, None, deadline)
> grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
> 	status = StatusCode.UNAVAILABLE
> 	details = "failed to connect to all addresses"
> 	debug_error_string = "{"created":"@1580929237.616755074","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1580929237.616752576","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"

**Comment by sniazhana-p** [comment] 2020-02-05 19:07
Trying to register a wrokflow against flyte running in docker on mac k8s instance:
 `flyte-cli -h localhost:30081 register-project --identifier myuniqueworkflow --name FriendlyWorkflowName -d "This is awesome workflow"` gives similar error:

> File "/usr/local/bin/flyte-cli", line 10, in <module>
>     sys.exit(_flyte_cli())
>   File "/Users/aliaksandrp/Library/Python/3.7/lib/python/site-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/Users/aliaksandrp/Library/Python/3.7/lib/python/site-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/Users/aliaksandrp/Library/Python/3.7/lib/python/site-packages/click/core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/Users/aliaksandrp/Library/Python/3.7/lib/python/site-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/Users/aliaksandrp/Library/Python/3.7/lib/python/site-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/flytekit/clis/flyte_cli/main.py", line 1502, in register_project
>     client.register_project(_Project(identifier, name, description))
>   File "/usr/local/lib/python3.7/site-packages/flytekit/clients/friendly.py", line 858, in register_project
>     project=project.to_flyte_idl(),
>   File "/usr/local/lib/python3.7/site-packages/flytekit/clients/raw.py", line 78, in handler
>     return fn(*args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/flytekit/clients/raw.py", line 558, in register_project
>     return self._stub.RegisterProject(project_register_request, metadata=self._metadata)
>   File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 824, in __call__
>     return _end_unary_response_blocking(state, call, False, None)
>   File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 726, in _end_unary_response_blocking
>     raise _InactiveRpcError(state)
> grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
> 	status = StatusCode.UNAVAILABLE
> 	details = "failed to connect to all addresses"
> 	debug_error_string = "{"created":"@1580929064.529186000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3941,"referenced_errors":[{"created":"@1580929064.529162000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":393,"grpc_status":14}]}"

**Comment by apryiomka** [comment] 2020-02-05 19:12
It seems like a dupe of https://github.com/lyft/flyte/issues/156

**Comment by kumare3** [comment] 2020-02-09 15:46
Yes This is a duplicate. I will close so that we can have one tracker issue!

**Closed by kumare3** 2020-02-09 15:46 UTC
